export interface Campana {
    // id_campana: number,
    // nombre_campana: string,
    // fecha_inicio: string,
    // fecha_fin: string,
    // fecha_fin_registro: string,
    // presupuesto: number,
    // nombre_responsable: string,
    // tarifa_base: number,
    // taller_brandeo: string,
    // carroceria_capo: boolean,
    // puerta_conductor: boolean,
    // puerta_pasajero: boolean,
    // puerta_traseratzq: boolean,
    // puerta_traseraDer: boolean,
    // carroceria_guantera: boolean,
    // carroceria_techo: boolean,
    // fecha_creacion: string,
    // fecha_modificacion: string,
    // estado: number,
    // id_empresa: number

    id_campana: number,
    nombre_campana: string,
    correo_responsable: string,
    id_sector: number,
    fecha_inicio: string,
    fecha_fin: string,
    fecha_fin_registro: string,
    presupuesto: number,
    nombre_responsable: string,
    tarifa_base: number,
    tarifa_min: number,
    tarifa_max: number,
    hora_monetizable_inicio: string,
    hora_monetizable_fin: string,
    cobro_minimo: number,
    tipo_brandeo: string,
    taller_brandeo: string,
    carroceria_capo: boolean,
    puerta_conductor: boolean,
    puerta_pasajero: boolean,
    puerta_traseratzq: boolean,
    puerta_traseraDer: boolean,
    carroceria_guantera: boolean,
    carroceria_techo: boolean,
    fecha_creacion: string,
    fecha_modificacion: string,
    estado: number,
    sedan_admisible: boolean,
    suv_admisible: boolean,
    camion_admisible: boolean,
    camioneta_admisible: boolean,
    bus_admisible: boolean,
    id_empresa: number,
}
