export interface Campana {
    id_campana: number,
    nombre_campana: string,
    fecha_inicio: string,
    fecha_fin: string,
    fecha_fin_registro: string,
    presupuesto: number,
    nombre_responsable: string,
    tarifa_base: number,
    taller_brandeo: string,
    carroceria_capo: boolean,
    puerta_conductor: boolean,
    puerta_pasajero: boolean,
    puerta_traseratzq: boolean,
    puerta_traseraDer: boolean,
    carroceria_guantera: boolean,
    carroceria_techo: boolean,
    fecha_creacion: string,
    fecha_modificacion: string,
    estado: number,
    id_empresa: number
}
