export interface Client {
    id_cliente?: number,
    cedula_cliente: string,
    nombre: string,
    apellido: string,
    fecha_nacimiento: string,
    email: string,
    sexo: number,
    telefono: string,
    estado: number,
    id_usuario?: number,
    id_empresa?: number,
    id_campana?: number,
    id_pais: number,
    id_ciudad: number,
}
