export interface FormularioAplicacion {
    id_formulario?: number,
    telefono_conductor: number,
    licencia: File | string,
    matricula: File | string,
    numero_cuenta_bancaria: string,
    cedula: string,
    entidad_bancaria: number,
    tipo_cuenta_bancaria: string,
    correo_electronico: string,
    fecha_envio: Date | string,
    id_usuario: number,
    id_ciudad: number,
    id_pais: number,
    id_vehiculo: number,
    id_campana: number,
    estado_solicitud: string,
    brandeo?: boolean,
}
